version: '2'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      # Only start a subset of services required for testing.
      - SERVICES=s3,sns,sqs,apigateway,lambda,dynamodb,dynamodbstreams,cloudformation
#      - DEBUG=${DEBUG- }
#      - DATA_DIR=${DATA_DIR- }
#      - PORT_WEB_UI=${PORT_WEB_UI- }
#      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
#      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
#      - DOCKER_HOST=unix:///var/run/docker.sock
#      - HOST_TMP_FOLDER=${TMPDIR}
#     volumes:
#       - "./localstack:/tmp/localstack}"
#       - "/var/run/docker.sock:/var/run/docker.sock"