export const regionsVietnam = [
  { id: 1, countryCode: 'VN', code: '01', name: 'Thành phố Hà Nội' },
  { id: 2, countryCode: 'VN', code: '02', name: 'Tỉnh Hà Giang' },
  { id: 3, countryCode: 'VN', code: '04', name: 'Tỉnh Cao Bằng' },
  { id: 4, countryCode: 'VN', code: '06', name: 'Tỉnh Bắc Kạn' },
  { id: 5, countryCode: 'VN', code: '08', name: 'Tỉnh Tuyên Quang' },
  { id: 6, countryCode: 'VN', code: '10', name: 'Tỉnh Lào Cai' },
  { id: 7, countryCode: 'VN', code: '11', name: 'Tỉnh Điện Biên' },
  { id: 8, countryCode: 'VN', code: '12', name: 'Tỉnh Lai Châu' },
  { id: 9, countryCode: 'VN', code: '14', name: 'Tỉnh Sơn La' },
  { id: 10, countryCode: 'VN', code: '15', name: 'Tỉnh Yên Bái' },
  { id: 11, countryCode: 'VN', code: '17', name: 'Tỉnh Hoà Bình' },
  { id: 12, countryCode: 'VN', code: '19', name: 'Tỉnh Thái Nguyên' },
  { id: 13, countryCode: 'VN', code: '20', name: 'Tỉnh Lạng Sơn' },
  { id: 14, countryCode: 'VN', code: '22', name: 'Tỉnh Quảng Ninh' },
  { id: 15, countryCode: 'VN', code: '24', name: 'Tỉnh Bắc Giang' },
  { id: 16, countryCode: 'VN', code: '25', name: 'Tỉnh Phú Thọ' },
  { id: 17, countryCode: 'VN', code: '26', name: 'Tỉnh Vĩnh Phúc' },
  { id: 18, countryCode: 'VN', code: '27', name: 'Tỉnh Bắc Ninh' },
  { id: 19, countryCode: 'VN', code: '30', name: 'Tỉnh Hải Dương' },
  { id: 20, countryCode: 'VN', code: '31', name: 'Thành phố Hải Phòng' },
  { id: 21, countryCode: 'VN', code: '33', name: 'Tỉnh Hưng Yên' },
  { id: 22, countryCode: 'VN', code: '34', name: 'Tỉnh Thái Bình' },
  { id: 23, countryCode: 'VN', code: '35', name: 'Tỉnh Hà Nam' },
  { id: 24, countryCode: 'VN', code: '36', name: 'Tỉnh Nam Định' },
  { id: 25, countryCode: 'VN', code: '37', name: 'Tỉnh Ninh Bình' },
  { id: 26, countryCode: 'VN', code: '38', name: 'Tỉnh Thanh Hóa' },
  { id: 27, countryCode: 'VN', code: '40', name: 'Tỉnh Nghệ An' },
  { id: 28, countryCode: 'VN', code: '42', name: 'Tỉnh Hà Tĩnh' },
  { id: 29, countryCode: 'VN', code: '44', name: 'Tỉnh Quảng Bình' },
  { id: 30, countryCode: 'VN', code: '45', name: 'Tỉnh Quảng Trị' },
  { id: 31, countryCode: 'VN', code: '46', name: 'Tỉnh Thừa Thiên Huế' },
  { id: 32, countryCode: 'VN', code: '48', name: 'Thành phố Đà Nẵng' },
  { id: 33, countryCode: 'VN', code: '49', name: 'Tỉnh Quảng Nam' },
  { id: 34, countryCode: 'VN', code: '51', name: 'Tỉnh Quảng Ngãi' },
  { id: 35, countryCode: 'VN', code: '52', name: 'Tỉnh Bình Định' },
  { id: 36, countryCode: 'VN', code: '54', name: 'Tỉnh Phú Yên' },
  { id: 37, countryCode: 'VN', code: '56', name: 'Tỉnh Khánh Hòa' },
  { id: 38, countryCode: 'VN', code: '58', name: 'Tỉnh Ninh Thuận' },
  { id: 39, countryCode: 'VN', code: '60', name: 'Tỉnh Bình Thuận' },
  { id: 40, countryCode: 'VN', code: '62', name: 'Tỉnh Kon Tum' },
  { id: 41, countryCode: 'VN', code: '64', name: 'Tỉnh Gia Lai' },
  { id: 42, countryCode: 'VN', code: '66', name: 'Tỉnh Đắk Lắk' },
  { id: 43, countryCode: 'VN', code: '67', name: 'Tỉnh Đắk Nông' },
  { id: 44, countryCode: 'VN', code: '68', name: 'Tỉnh Lâm Đồng' },
  { id: 45, countryCode: 'VN', code: '70', name: 'Tỉnh Bình Phước' },
  { id: 46, countryCode: 'VN', code: '72', name: 'Tỉnh Tây Ninh' },
  { id: 47, countryCode: 'VN', code: '74', name: 'Tỉnh Bình Dương' },
  { id: 48, countryCode: 'VN', code: '75', name: 'Tỉnh Đồng Nai' },
  { id: 49, countryCode: 'VN', code: '77', name: 'Tỉnh Bà Rịa - Vũng Tàu' },
  { id: 50, countryCode: 'VN', code: '79', name: 'Thành phố Hồ Chí Minh' },
  { id: 51, countryCode: 'VN', code: '80', name: 'Tỉnh Long An' },
  { id: 52, countryCode: 'VN', code: '82', name: 'Tỉnh Tiền Giang' },
  { id: 53, countryCode: 'VN', code: '83', name: 'Tỉnh Bến Tre' },
  { id: 54, countryCode: 'VN', code: '84', name: 'Tỉnh Trà Vinh' },
  { id: 55, countryCode: 'VN', code: '86', name: 'Tỉnh Vĩnh Long' },
  { id: 56, countryCode: 'VN', code: '87', name: 'Tỉnh Đồng Tháp' },
  { id: 57, countryCode: 'VN', code: '89', name: 'Tỉnh An Giang' },
  { id: 58, countryCode: 'VN', code: '91', name: 'Tỉnh Kiên Giang' },
  { id: 59, countryCode: 'VN', code: '92', name: 'Thành phố Cần Thơ' },
  { id: 60, countryCode: 'VN', code: '93', name: 'Tỉnh Hậu Giang' },
  { id: 61, countryCode: 'VN', code: '94', name: 'Tỉnh Sóc Trăng' },
  { id: 62, countryCode: 'VN', code: '95', name: 'Tỉnh Bạc Liêu' },
  { id: 63, countryCode: 'VN', code: '96', name: 'Tỉnh Cà Mau' },
];
